settings:
  title: 'Status'
  url: 'https://status.unrealninjas.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Everything is looking real nice'
  notAllmonitorsOperational: 'Something is being fucky'
  monitorLabelOperational: 'Healthy'
  monitorLabelNotOperational: 'Problems'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: unrealninjas-com
    name: Main
    description: 'Main site for Unreal Ninjas.'
    url: 'https://unrealninjas.com'
    method: GET
    expectStatus: 200

  - id: f000-backblazeb2-com
    name: Image Sharing
    description: 'Image sharing thanks to the B2/CF Bandwidth Alliance.'
    url: 'https://img.unrealninjas.com'
    method: GET
    expectStatus: 400 # 400 is good, the client just isn't asking for a filename so it is considered a bad request.
