settings:
  title: 'System Status'
  url: 'https://status.unrealninjas.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Everything is looking real nice ðŸ’ª'
  notAllmonitorsOperational: 'Something is being fucky ðŸ¤¬'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Misbehaving'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: unrealninjas-com
    name: unrealninjas.com
    description: 'The one and only abomination.'
    url: 'https://unrealninjas.com'
    method: GET
    expectStatus: 200

  - id: s3-us-west-000-endpoint
    name: img.unrealninjas.com
    description: 'Image sharing thanks to the B2/CF Bandwidth Alliance.'
    url: 's3.us-west-000.backblazeb2.com'
    method: GET
    expectStatus: 403 # s3.us-west-000 endpoint indicates that the server understood the request so it's likely operational
